# Generated by Django 3.1 on 2020-08-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='Worker',
            new_name='worker',
        ),
    ]
