# Generated by Django 3.1 on 2020-08-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('image_profile', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('is_available', models.BooleanField()),
                ('primary_phone', models.CharField(max_length=10)),
                ('secondary_phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
            ],
        ),
    ]
